name: 'Internal version string generator'
description: 'Generate different types of version strings for internal use'
outputs:
  version:
    description: Contains major and minor version, in the format of <major>.<minor>
    value: ${{ steps.semver-parser.outputs.major }}.${{ steps.semver-parser.outputs.minor }}
  patch:
    description: Contains patch version
    value: ${{ steps.semver-parser.outputs.patch }}
  sha:
    description: Contains short Git SHA
    value: ${{ steps.commit.outputs.short }}
runs:
  using: composite
  steps:
    - name: Get version from package.json
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Parse semver string
      id: semver-parser
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{ steps.package-version.outputs.current-version }}

    - name: Get HEAD commit hash
      id: commit
      uses: pr-mpt/actions-commit-hash@v2
