services:
  bot:
    # points to the root of this repository
    build: ../../.
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOGS_FILENAME=/var/log/wisdom-bot/nest-%DATE%.log
    volumes:
      - ./logs:/var/log/wisdom-bot
