services:
  bot:
    build: jonfelixrico/wisdom-bot:latest
    # build: jonfelixrico/wisdom-bot:alpha
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOGS_FILENAME=/var/log/wisdom-bot/nest-%DATE%.log
    volumes:
      - ./logs:/var/log/wisdom-bot
