name: Alpha pipeline

on:
  push:
    branches:
      - develop-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Generate version strings
        uses: './.github/actions/internal-version-string-generator'
        id: version-generator
        with:
          pre-release-label: alpha
      - name: 'Show generated strings'
        run: |
          echo Docker string: ${{ steps.version-generator.outputs.docker }}
          echo App string: ${{ steps.version-generator.outputs.app }}
      - name: package.json info
        uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ steps.version-generator.outputs.app }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jonfelixrico/wisdom-bot:${{ steps.version-generator.outputs.docker }},jonfelixrico/wisdom-bot:alpha
