name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Get package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wisdom-bot:${{ steps.package-version.outputs.current-version}}
